version: 2
jobs:
    # Run NightWatch End-2-End Tests
    e2e_tests:
        docker:
            - image: circleci/node:8.11-browsers
        working_directory: ~/vue-circleci
        steps:
            - attach_workspace:
                  at: ~/vue-circleci
            - run: mkdir e2e-reports
            - run:
                  name: Download Selenium
                  command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
            - run:
                  name: Start Selenium
                  command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
                  background: true
            - run: npm run e2e
            - store_artifacts:
                  path: e2e-reports/
            - store_test_results:
                  path: e2e-reports/
    # Build the project
    build:
        docker:
            - image: circleci/node:8.11-browsers
        working_directory: ~/vue-circleci
        steps:
            - attach_workspace:
                  at: ~/vue-circleci
            - run: npm run build
            - persist_to_workspace:
                  root: .
                  paths: .
