version: 2
jobs:
    build:
        docker:
            - image: webpackcontrib/circleci-jdk9-node8
        parallelism: 1
        working_directory: ~/app
        steps:
            - checkout

            - run: mkdir test-reports

            - run:
                   name: Download Selenium
                   command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

            - run:
                  name: Start Selenium
                  command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
                  background: true

            - attach_workspace:
                  at: ~/app
            - restore_cache:
                  key: multi-currency-app-{{ checksum "yarn.lock" }}
            - run: npm install
            - save_cache:
                  key: multi-currency-app-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules
            - run: npm run build
            - persist_to_workspace:
                  root: .
                  paths: dist
            - run: npm test --coverage
