version: 2
jobs:
    build:
        docker:
            - image: webpackcontrib/circleci-jdk9-node8
        parallelism: 1
        working_directory: ~/app
        steps:
            - checkout

            - run:
                name: Configure dependencies
                command: |
                    curl -o- -L https://yarnpkg.com/install.sh | bash
                    source ~/.bashrc

            - attach_workspace:
                  at: ~/app
            - restore_cache:
                  key: multi-currency-app-{{ checksum "yarn.lock" }}
            - run: yarn install
            - save_cache:
                  key: multi-currency-app-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules
            - run: yarn build
            - persist_to_workspace:
                  root: .
                  paths: dist
            - run: yarn test --coverage
