version: 2
jobs:
    build:
        docker:
            - image: webpackcontrib/circleci-jdk9-node8
        parallelism: 1
        working_directory: ~/app
        steps:
            - checkout

            - attach_workspace:
                  at: ~/app
            - restore_cache:
                  key: multi-currency-app-{{ checksum "yarn.lock" }}
            - run: npm install
            - save_cache:
                  key: multi-currency-app-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules
            - run: npm run build
            - persist_to_workspace:
                  root: .
                  paths: dist
            - run: npm test --coverage
